---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/auth/login":
    post:
      summary: Login user
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    message: Logged in successfully.
                    token: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI5ZjdhNGE3OC1iMDE0LTQ0ZTUtYjExOC1lYWEwNTYwNjExZmEiLCJzdWIiOiJjZjg2NGE5NC0xMmYwLTRiYmUtYTE2ZC1hNDBhNTI5NmIyMjgiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE3NDY2NzIyNTAsImV4cCI6MTc0Njc1ODY1MH0.HLYoKSgdPr_em25WRHz7aQ1cOf8Y9VBzFX4u9hH2ouo
                    refresh_token:
                      value: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjZjg2NGE5NC0xMmYwLTRiYmUtYTE2ZC1hNDBhNTI5NmIyMjgiLCJqdGkiOiI5ZjdhNGE3OC1iMDE0LTQ0ZTUtYjExOC1lYWEwNTYwNjExZmEifQ.8tFmFkrpcqMJe0u92m2FOCT1T5ekS0D4WTXsRGdEHoM
                      httponly: true
                      expires: '2025-05-09T02:44:10.156Z'
                      secure: false
                    user:
                      id: cf864a94-12f0-4bbe-a16d-a40a5296b228
                      avatar:
                        id: 
                        attachment_id: 
                        content_type: 
                        url: 
                      email: test@test
                      full_name: Doria Schroeder
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/auth/requests/login"
  "/api/auth/signup":
    post:
      summary: Sign up user
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    message: Signed up successfully.
                    token: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJmZDYzNGVjYS0zMTJkLTRjZmItOWQ0ZS03ZjBhZDMyNTE2NTMiLCJzdWIiOiJkNzJhMTdkNi03OWNjLTQzMDAtYjBhMC1mODQzNDViNTllNWYiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE3NDY2NzIyNTAsImV4cCI6MTc0Njc1ODY1MH0.Na9_jqgj4e6Hy-cJ2CKlojSPehchZnG-Dp1tp4n0aec
                    user:
                      id: d72a17d6-79cc-4300-b0a0-f84345b59e5f
                      avatar:
                        id: 
                        attachment_id: 
                        content_type: 
                        url: 
                      email: teste@teste
                      full_name: 
                    refresh_token:
                      value: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkNzJhMTdkNi03OWNjLTQzMDAtYjBhMC1mODQzNDViNTllNWYiLCJqdGkiOiJmZDYzNGVjYS0zMTJkLTRjZmItOWQ0ZS03ZjBhZDMyNTE2NTMifQ.L4ZOWN-IujTjvMwA4PM1wVQfxwB1PQsRwp3RlXWKeGU
                      httponly: true
                      expires: '2025-05-09T02:44:10.201Z'
                      secure: false
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/auth/requests/signup"
  "/api/auth/logout":
    delete:
      summary: Logout User
      tags:
      - Auth
      security:
      - bearer_auth: []
      responses:
        '200':
          description: Successful
  "/api/v1/mentor/profiles/{id}":
    get:
      summary: Show Mentor Profile
      tags:
      - Mentor Profiles
      security:
      - bearer_auth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    data:
                      id: 64e9dee6-2da2-4da4-a791-bce4f7a5d38e
                      availabilities: []
                      bio: Porro dignissimos ipsa. Sit consequatur corrupti. Alias
                        nihil ratione.
                      client_profiles: []
                      expertise_areas: []
                      headline: Principal Orchestrator
                      hourly_rate: '39.92'
                      linkedin_url: http://linkedin.com/kristen_smitham
                      profile_name: 
                      rating: 7.99
                      sessions: []
                      years_of_experience: 9
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      auth: You need to sign in or sign up before continuing.
        '404':
          description: Not found
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      base:
                      - Couldn't find Mentor::Profile with 'id'=not_an_id
                    request_id: 2acafa42-cb64-412c-a8fa-0a90862fe0c4
    put:
      summary: Update Mentor Profile
      tags:
      - Mentor Profiles
      security:
      - bearer_auth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    data:
                      id: 5d89ad27-6e42-46b8-a295-5d69ccb448d0
                      availabilities: []
                      bio: Updated Bio
                      client_profiles: []
                      expertise_areas: []
                      headline: Updated Headline
                      hourly_rate: '50.0'
                      linkedin_url: https://linkedin.com/in/updated
                      profile_name: Updated Profile
                      rating: 4.5
                      sessions: []
                      years_of_experience: 5
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      auth: You need to sign in or sign up before continuing.
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/v1/mentor/profile/requests/update"
  "/api/v1/users/{id}":
    get:
      summary: Show User
      tags:
      - Users
      security:
      - bearer_auth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    data:
                      id: 4e286ecf-3ddc-45b1-9a0a-32b231665707
                      avatar:
                        id: 
                        attachment_id: 
                        content_type: 
                        url: 
                      cpf: '04530730263'
                      email: jacquelyne.grady@legros.test
                      full_name: Cristine Ruecker
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      auth: You need to sign in or sign up before continuing.
        '404':
          description: Not found
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      base:
                      - Couldn't find User with 'id'=not_an_id
                    request_id: 755f18c4-4370-4c12-ba05-38d57c3eb76a
    put:
      summary: Update User
      tags:
      - Users
      security:
      - bearer_auth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    data:
                      id: 1a25520a-fcf7-4015-9b4b-4e8cce254c6b
                      avatar:
                        id: 
                        attachment_id: 
                        content_type: 
                        url: 
                      cpf: '12496062095'
                      email: admin@acme.com
                      full_name: Dummy Name
        '422':
          description: Unprocessable entity
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      email:
                      - is invalid
                    request_id: 4677a2e7-bf72-430b-8df3-3c8708a9db09
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      auth: You need to sign in or sign up before continuing.
        '404':
          description: Not found
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      base:
                      - Couldn't find User with 'id'=not_an_id
                    request_id: 1c6437dd-0a1c-49ed-97e8-790dd4811a81
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/v1/users/requests/update"
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
  schemas:
    auth:
      requests:
        login:
          title: User Login Request
          type: object
          properties:
            user:
              type: object
              properties:
                email:
                  type: string
                  example: t@t.com
                password:
                  type: string
                  example: '123456'
              required:
              - email
              - password
          required:
          - user
        signup:
          title: Create User Request
          type: object
          properties:
            user:
              type: object
              properties:
                email:
                  type: string
                  example: test@test
                password:
                  type: string
                full_name:
                  type: string
              required:
              - email
              - password
      responses:
        login:
          title: Create User Response
          type: object
          properties:
            message:
              type: string
            token:
              type: string
            refresh_token:
              type: object
              properties:
                value:
                  type: string
                httponly:
                  type: boolean
                expires:
                  type: string
                secure:
                  type: boolean
            user:
              "$ref": "#/components/schemas/v1/users/_common"
        signup:
          title: Create User Response
          type: object
          properties:
            message:
              type: string
            token:
              type: string
            refresh_token:
              type: object
              properties:
                value:
                  type: string
                httponly:
                  type: boolean
                expires:
                  type: string
                secure:
                  type: boolean
    common:
      pagination_meta:
        title: Pagination Meta
        type: object
        properties:
          current_page:
            type: integer
          total_pages:
            type: integer
          current_page_size:
            type: integer
          total:
            type: integer
        required:
        - current_page
        - total_pages
        - current_page_size
        - total
    v1:
      mentor:
        availabilities:
          _common:
            title: Mentor Availability
            type: object
            additionalProperties: true
            properties:
              id:
                type: string
              start_time:
                type: string
                format: date-time
              end_time:
                type: string
                format: date-time
          _private:
            title: Mentor Availability Private
            type: object
            additionalProperties: true
            properties:
              id:
                type: string
              start_time:
                type: string
                format: date-time
              end_time:
                type: string
                format: date-time
        expertise_areas:
          _common:
            title: Mentor ExpertiseArea
            type: object
            additionalProperties: true
            properties:
              id:
                type: string
              name:
                type: string
        profiles:
          _common:
            title: Mentor Profile
            type: object
            additionalProperties: true
            properties:
              id:
                type: string
              bio:
                type: string
              headline:
                type: string
                nullable: true
              hourly_rate:
                type: string
                nullable: true
              linkedin_url:
                type: string
                nullable: true
              profile_name:
                type: string
                nullable: true
              rating:
                type: number
                format: float
                nullable: true
              years_of_experience:
                type: integer
                nullable: true
              expertise_areas:
                type: array
                items:
                  "$ref": "#/components/schemas/v1/mentor/expertise_areas/_common"
              availabilities:
                type: array
                items:
                  "$ref": "#/components/schemas/v1/mentor/availabilities/_common"
          _private:
            title: Mentor Profile Private
            type: object
            additionalProperties: true
            allOf:
            - "$ref": "#/components/schemas/v1/mentor/profiles/_common"
            properties:
              sessions:
                type: array
                items:
                  "$ref": "#/components/schemas/v1/mentor/session"
              client_profiles:
                type: array
                items:
                  "$ref": "#/components/schemas/v1/mentor/profiles/_common"
          requests:
            update:
              title: Update Mentor Profile Request
              type: object
              properties:
                mentor_profile:
                  type: object
                  properties:
                    bio:
                      type: string
                      nullable: true
                    headline:
                      type: string
                      nullable: true
                    hourly_rate:
                      type: string
                      nullable: true
                    linkedin_url:
                      type: string
                      nullable: true
                    profile_name:
                      type: string
                      nullable: true
                    rating:
                      type: number
                      nullable: true
                    years_of_experience:
                      type: string
                      nullable: true
                  required:
                  - mentor_profile
          responses:
            show:
              title: Show Mentor Profile Response
              type: object
              properties:
                data:
                  "$ref": "#/components/schemas/v1/mentor/profiles/_private"
              required:
              - data
            update:
              title: Update Mentor Profile Response
              type: object
              properties:
                data:
                  "$ref": "#/components/schemas/v1/mentor/profiles/_private"
              required:
              - data
      users:
        _common:
          title: User
          type: object
          additionalProperties: true
          properties:
            id:
              type: string
            full_name:
              type: string
              nullable: true
            email:
              type: string
              nullable: true
        _private:
          title: User Private
          type: object
          additionalProperties: true
          properties:
            id:
              type: string
            full_name:
              type: string
            email:
              type: string
              nullable: true
            cpf:
              type: string
              nullable: true
        requests:
          update:
            title: Update User Request
            type: object
            properties:
              user:
                type: object
                properties:
                  full_name:
                    type: string
                  cpf:
                    type: string
                    nullable: true
                  email:
                    type: string
                    nullable: true
                required:
                - user
        responses:
          show:
            title: Show User Response
            type: object
            properties:
              data:
                "$ref": "#/components/schemas/v1/users/_private"
            required:
            - data
servers:
- url: http://localhost:3000
